/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AeriaBadge: typeof import('@aeria-ui/ui')['AeriaBadge']
    AeriaCrud: typeof import('@aeria-ui/ui')['AeriaCrud']
    AeriaCrudColumn: typeof import('@aeria-ui/ui')['AeriaCrudColumn']
    AeriaIcon: typeof import('@aeria-ui/ui')['AeriaIcon']
    AeriaMain: typeof import('@aeria-ui/ui')['AeriaMain']
    AeriaPicture: typeof import('@aeria-ui/ui')['AeriaPicture']
    NoResults: typeof import('./../src/components/no-results.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
