/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard': RouteRecordInfo<'/dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/asset': RouteRecordInfo<'/dashboard/asset', '/dashboard/asset', Record<never, never>, Record<never, never>>,
    '/dashboard/employeDetail/[id]': RouteRecordInfo<'/dashboard/employeDetail/[id]', '/dashboard/employeDetail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/employee/': RouteRecordInfo<'/dashboard/employee/', '/dashboard/employee', Record<never, never>, Record<never, never>>,
    '/dashboard/equipmentRelease': RouteRecordInfo<'/dashboard/equipmentRelease', '/dashboard/equipmentRelease', Record<never, never>, Record<never, never>>,
  }
}
